serve: true
exclude: ['Gemfile', 'Gemfile.lock', 'README.textile', 'import.rb', 'downmark_it.rb']
permalink: /p/:title
paginate: 5
paginate_path: "blog/page/:num"
markdown: rdiscount
url: http://rafael.adm.br